### ISSUE TITLE
Figure out how to clear GUI displaying without clearing stored data for v1.2.1

### ISSUE THREAD

**Issue by Cheng20010201** [AY2021S2-CS2103T-T13-1/tp#26]
As per title.

This is helpful for v1.2, when we want to clear the previous displaying aftering entering a new mode. (e.g. go to study mode from learn mode, go back to learn mode from study mode)

**Comment by Cheng20010201** [comment]
This is just to 'figure out', so after you know what is going on you can just self-close it or create a draft PR containing the experiment you ran with the code base.

**Comment by xinweit** [comment]
Figured out logic behind GUI display
