### ISSUE TITLE
Figure out how to display some different content in GUI for v1.2.1

### ISSUE THREAD

**Issue by Cheng20010201** [AY2021S2-CS2103T-T13-1/tp#27]
As per title.

This will be useful for displaying some welcome message after the app is initiated.

**Comment by Cheng20010201** [comment]
This is just to 'figure out', so after you know what is going on you can just self-close it or create a draft PR containing the experiment you ran with the code base.

**Comment by xinweit** [comment]
Added greetings message for the app.

**Comment by Cheng20010201** [comment]
> Added greetings message for the app.

Perhaps create a PR for it, as it will probably be something useful for the application? :)

**Comment by xinweit** [comment]
> > Added greetings message for the app.
> 
> Perhaps create a PR for it, as it will probably be something useful for the application? :)
Sure yucheng, created the PR
