### ISSUE TITLE
(Potential) issue when entering 'start'

### ISSUE THREAD

**Issue by Cheng20010201** [AY2021S2-CS2103T-T13-1/tp#63]
Now after entering 'start', no matter which state the application is in, a quiz session will be started.
E.g. 
1. When in learn mode, 
2. When in welcome page
3. When inside a quiz session

'start' will start a quiz directly in these 3 situations.

Is it a feature or a bug?

**Comment by xinweit** [comment]
Should only be able to start when user is in quiz mode I think. Working on it.
